[ lint ] Please the linter

diff --git a/ncd-xz b/ncd-xz
--- a/ncd-xz
+++ b/ncd-xz
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 if ! xz --version >/dev/null 2>/dev/null
-  then echo 'Cannot find `xz` command' >&2; exit 2
+  then echo "Cannot find \`xz\` command" >&2; exit 2
 fi
 
 fileExists() {
