[ lint ] Format the original shell script (what was wrong with me then?)

diff --git a/ncd-xz b/ncd-xz
--- a/ncd-xz
+++ b/ncd-xz
@@ -1,16 +1,19 @@
 #!/bin/sh
 
-if ! xz --version >/dev/null 2>/dev/null
-  then echo "Cannot find \`xz\` command" >&2; exit 2
+if ! xz --version > /dev/null 2> /dev/null; then
+  echo "Cannot find \`xz\` command" >&2
+  exit 2
 fi
 
 fileExists() {
-  if [ -z "$1" ]
-    then echo "Usage: $0 <file1> <file2>" >&2; exit 3
+  if [ -z "$1" ]; then
+    echo "Usage: $0 <file1> <file2>" >&2
+    exit 3
   fi
 
-  if [ ! -r "$1" ]
-    then echo "Argument \"$1\" must be a readable file" >&2; exit 4
+  if [ ! -r "$1" ]; then
+    echo "Argument \"$1\" must be a readable file" >&2
+    exit 4
   fi
 }
 
